SELECT PHARMACODE, ASW_ITEMNR, PLANT, SAP_MATNR_TO_BE, CREATED FROM SAP_MATERIAL_NUMBER:INSERT INTO TEST_SAP_MATERIAL_NUMBER VALUES (?, ?, ?, ?, ?)
SELECT PHARMACODE, ASW_ITEMNR, PLANT, SAP_MATNR_TO_BE, CREATED FROM SAP_MATERIAL_NUMBER:INSERT INTO TEST1_SAP_MATERIAL_NUMBER VALUES (?, ?, ?, ?, ?)
